source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Edamame_Example' do
  pod 'Edamame', :path => '../'
  pod 'MirrorObject'
  pod 'RxSwift'
  pod 'RxCocoa'
end

target 'Edamame_Tests' do
  pod 'Edamame', :path => '../'
end

